### ISSUE TITLE
[Question] Will AMDGPU or EVDI have better support for the other now?

### ISSUE THREAD

**Issue by NikhilSaini38** [pioto1225/evdi#5]
I tried using default branch of EVDI recently after seeing your update about retiring this branch in README. But results were still laggy, so i had to revert to your branch. What should I be expecting from EVDI, i couldn't find any  any recent news regarding EVDI and AMDGPU. Can you please let me know where to follow the news regarding the same if there is any

**Comment by pioto1225** [comment]
I think you can follow these links to get updates, asking a question on the forum or raising a ticket on github sometimes works and you get feedback:
- https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
- https://displaylink.org/forum/forumdisplay.php?f=29
- https://github.com/DisplayLink/evdi

W.r.t amdgpu, I just noticed yesterday that DisplayLink has added a [change](https://github.com/DisplayLink/evdi/commit/4f4687c2a0d0a552b4f3aba6ef3df421169b8191) similar to the one I have on this branch which should speed up X11 (I suppose this is what you are using). The fix is automatic (no vmap_texture required). The change is present in their github repo,  not (yet?) in their binary driver which was released in March. So if you install the latest binary driver and then build and install their kernel module from [here](https://github.com/DisplayLink/evdi) instead of my branch, I reckon it should have the same performance.

**Comment by NikhilSaini38** [comment]
Thanks for the information.
